In [1]:
pip install pandas

Requirement already satisfied: pandas in c:\Users\maria\AppData\Local\Programs\Python\Python313\Lib\site-packages (3.0.6)
Requirement already satisfied: numpy>=1.26.0 in c:\Users\maria\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\maria\AppData\Roaming\Python\Python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\maria\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2026.5)
Requirement already satisfied: six>=1.5 in C:\Users\maria\AppData\Roaming\Python\Python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [9]:
import pandas as pd
print(f"Versión de Pandas: {pd.__version__}")

Versión de Pandas: 3.0.6

In [16]:
%pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   ---------------------------------------- 0/2 [et-xmlfile]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5
Note: you may need to restart the kernel to use updated packages.

Conceptos Clave:

Series: Arreglo unidimensional etiquetado
DataFrame: Estructura bidimensional tipo tabla
Índices: Etiquetas para acceder a los datos

In [4]:
# SERIES
# Una serie es una columna

edades = pd.Series([20,25,30])

edades

0    20
1    25
2    30
dtype: int64

In [5]:
# DATAFRAME
# Un Dataframe es una tabla

datos = {
    "Nombre":["Ana","Luis","Pedro"],
    "Edad":[20,25,30],
    "Ciudad":["Bogotá","Pereira","Cali"]
}

df = pd.DataFrame(datos) #df signifa base de datos df

df

  Nombre  Edad   Ciudad
0    Ana    20   Bogotá
1   Luis    25  Pereira
2  Pedro    30     Cali

In [17]:
clientes = pd.read_excel("Clientes.xlsx")

In [18]:
ventas = pd.read_excel("Ventastaller.xlsx")

In [19]:
clientes.head() # Muestra las primeras 5 filas

  id_cliente nombre_cliente     ciudad segmento
0        C01     Ana Torres    Pereira  Premium
1        C02     Luis Gómez  Manizales  Regular
2        C03    María López    Armenia  Premium
3        C04    Carlos Ruiz    Pereira  Regular
4        C05  Sofía Herrera       Cali  Premium

In [20]:
clientes.tail() # Muestra las ultimas filas

  id_cliente nombre_cliente     ciudad segmento
5        C06    Juan Castro   Medellín  Regular
6        C07  Valentina Gil     Bogotá  Premium
7        C08   Andrés Mejía    Armenia  Regular
8        C09    Laura Rojas    Pereira  Premium
9        C10  Daniel Vargas  Manizales  Regular

Conociendo el Dataset

In [21]:
clientes.shape # Tamaño

(10, 4)

In [22]:
clientes.columns # Nombres de columnas

Index(['id_cliente', 'nombre_cliente', 'ciudad', 'segmento'], dtype='str')

In [23]:
clientes.info() # Información general

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_cliente      10 non-null     str
 1   nombre_cliente  10 non-null     str
 2   ciudad          10 non-null     str
 3   segmento        10 non-null     str
dtypes: str(4)
memory usage: 452.0 bytes

In [24]:
ventas.describe() # Estadísticas

                            Fecha   Cantidad  Precio_Unitario
count                          51  49.000000     5.100000e+01
mean   2026-01-25 03:17:38.823529   2.959184     1.030196e+06
min           2026-01-01 00:00:00   1.000000     8.500000e+04
25%           2026-01-12 12:00:00   1.000000     1.200000e+05
50%           2026-01-25 00:00:00   2.000000     8.500000e+05
75%           2026-02-06 12:00:00   4.000000     2.500000e+06
max           2026-02-19 00:00:00  10.000000     2.500000e+06
std                           NaN   2.449143     1.046791e+06

In [ ]:
clientes.dtypes #Tipo de dato de nuestro excel

id_cliente        str
nombre_cliente    str
ciudad            str
segmento          str
dtype: object

In [27]:
clientes.sample(10) # Muestra datos al azar

  id_cliente nombre_cliente     ciudad segmento
1        C02     Luis Gómez  Manizales  Regular
0        C01     Ana Torres    Pereira  Premium
7        C08   Andrés Mejía    Armenia  Regular
3        C04    Carlos Ruiz    Pereira  Regular
8        C09    Laura Rojas    Pereira  Premium
4        C05  Sofía Herrera       Cali  Premium
6        C07  Valentina Gil     Bogotá  Premium
5        C06    Juan Castro   Medellín  Regular
2        C03    María López    Armenia  Premium
9        C10  Daniel Vargas  Manizales  Regular

Seleccionar datos

In [ ]:
clientes["ciudad"] #mostrar datos de esa columna

0      Pereira
1    Manizales
2      Armenia
3      Pereira
4         Cali
5     Medellín
6       Bogotá
7      Armenia
8      Pereira
9    Manizales
Name: ciudad, dtype: str

In [ ]:
clientes[["nombre_cliente","segmento"]] #mostrar columnas especificas

  nombre_cliente segmento
0     Ana Torres  Premium
1     Luis Gómez  Regular
2    María López  Premium
3    Carlos Ruiz  Regular
4  Sofía Herrera  Premium
5    Juan Castro  Regular
6  Valentina Gil  Premium
7   Andrés Mejía  Regular
8    Laura Rojas  Premium
9  Daniel Vargas  Regular

In [33]:
# Filas

clientes.iloc[3]

id_cliente                C04
nombre_cliente    Carlos Ruiz
ciudad                Pereira
segmento              Regular
Name: 3, dtype: str

In [ ]:
clientes.iloc[0:5]  #Se usa para

  id_cliente nombre_cliente     ciudad segmento
0        C01     Ana Torres    Pereira  Premium
1        C02     Luis Gómez  Manizales  Regular
2        C03    María López    Armenia  Premium
3        C04    Carlos Ruiz    Pereira  Regular
4        C05  Sofía Herrera       Cali  Premium

Filtrar información

In [ ]:
# definir bajo una condicion o palabra de las columnas ciudades nombre cualquier cosa

clientes[clientes["ciudad"] == "Cali"]

  id_cliente nombre_cliente ciudad segmento
4        C05  Sofía Herrera   Cali  Premium

In [ ]:
#Se usa para cuando no se sabe con exactitud como se escribio la info, si usan tilde o no
clientes[clientes['ciudad'].str.startswith("Pe")] # Startswith - Empezar con tal letra

  id_cliente nombre_cliente   ciudad segmento
0        C01     Ana Torres  Pereira  Premium
3        C04    Carlos Ruiz  Pereira  Regular
8        C09    Laura Rojas  Pereira  Premium

In [40]:
#Se usa para cuando no se sabe con exactitud como se escribio la info, si usan tilde o no
clientes[clientes['nombre_cliente'].str.contains("Ju")] # Contains - contiene

  id_cliente nombre_cliente    ciudad segmento
5        C06    Juan Castro  Medellín  Regular

In [41]:
#Se usa para cuando no se sabe con exactitud como se escribio la info, si usan tilde o no
clientes[clientes['nombre_cliente'].str.endswith("ez")] # Endswith - Termine en tal letra

  id_cliente nombre_cliente     ciudad segmento
1        C02     Luis Gómez  Manizales  Regular
2        C03    María López    Armenia  Premium

CON CONDICIONALES +2

In [ ]:
# Dos condiciones
#Traer la base a analizar
clientes[
    (clientes["segmento"]== "Regular") & # & = and-y
    (clientes["ciudad"]=="Manizales") | # | = or-o
    (clientes["nombre_cliente"].str.startswith("Lu"))
]

  id_cliente nombre_cliente     ciudad segmento
1        C02     Luis Gómez  Manizales  Regular
9        C10  Daniel Vargas  Manizales  Regular

In [46]:
clientes_filtrados = [nombre_cliente for nombre_cliente in clientes["nombre_cliente"]
                    if "Luis" in nombre_cliente]

clientes_filtrados

['Luis Gómez']

Crear columnas nuevas

In [ ]:
ventas["IVA"] = ventas["Precio_Unitario"]*0.19 #Es para crear una nueva columna

In [48]:
ventas.head()

,ID_Venta,Fecha,Cliente,Ciudad,Producto,Categoría,Cantidad,Precio_Unitario,Estado,IVA
0,V001,2026-01-01,Ana Pérez,Pereira,Laptop,Tecnología,2.0,2500000,Completado,475000.0
1,V002,2026-01-02,Carlos Gómez,pereira,Mouse,tecnologia,5.0,85000,completado,16150.0
2,V003,2026-01-03,María Díaz,PEREIRA,Teclado,Tecnología,3.0,120000,COMPLETADO,22800.0
3,V004,2026-01-04,Juan López,Bogotá,Monitor,tecnologia,1.0,850000,Pendiente,161500.0
4,V005,2026-01-05,Laura Torres,bogota,Laptop,Tecnología,1.0,2500000,Completado,475000.0

In [49]:
ventas.columns

Index(['ID_Venta', 'Fecha', 'Cliente', 'Ciudad', 'Producto', 'Categoría',
       'Cantidad', 'Precio_Unitario', 'Estado', 'IVA'],
      dtype='str')

Mini reto
Usa la base de datos de ventas y responde

Preguntas:

Mostrar las primeras 10 filas.
Cuántas filas tiene?
Mostrar solo las columnas:
Producto
Precio
Mostrar únicamente productos mayores a $100.000.
Crear una columna Precio Final.
Mostrar únicamente productos de laptop.

In [53]:
#Mostrar las primeras 10 filas.

ventas.head(10)

,ID_Venta,Fecha,Cliente,Ciudad,Producto,Categoría,Cantidad,Precio_Unitario,Estado,IVA
0,V001,2026-01-01,Ana Pérez,Pereira,Laptop,Tecnología,2.0,2500000,Completado,475000.0
1,V002,2026-01-02,Carlos Gómez,pereira,Mouse,tecnologia,5.0,85000,completado,16150.0
2,V003,2026-01-03,María Díaz,PEREIRA,Teclado,Tecnología,3.0,120000,COMPLETADO,22800.0
3,V004,2026-01-04,Juan López,Bogotá,Monitor,tecnologia,1.0,850000,Pendiente,161500.0
4,V005,2026-01-05,Laura Torres,bogota,Laptop,Tecnología,1.0,2500000,Completado,475000.0
5,V006,2026-01-06,Pedro Ruiz,Medellín,Mouse,Tecnología,10.0,85000,Completado,16150.0
6,V007,2026-01-07,Ana Pérez,Pereira,Laptop,Tecnología,2.0,2500000,Completado,475000.0
7,V007,2026-01-07,Ana Pérez,Pereira,Laptop,Tecnología,2.0,2500000,Completado,475000.0
8,V008,2026-01-08,Sofía Castro,Cali,Teclado,TECNOLOGIA,4.0,120000,Completado,22800.0
9,V009,2026-01-09,Andrés Rojas,Cali,Monitor,Tecnología,NaN,850000,Pendiente,161500.0

In [71]:
#Cuántas filas tiene?
ventas.shape

(51, 11)

In [59]:
#Mostrar solo las columnas:
#Producto
#Precio
ventas[["Producto","Precio_Unitario"]]

   Producto  Precio_Unitario
0    Laptop          2500000
1     Mouse            85000
2   Teclado           120000
3   Monitor           850000
4    Laptop          2500000
5     Mouse            85000
6    Laptop          2500000
7    Laptop          2500000
8   Teclado           120000
9   Monitor           850000
10   Laptop          2500000
11    Mouse            85000
12  Teclado           120000
13  Monitor           850000
14   Laptop          2500000
15    Mouse            85000
16  Teclado           120000
17  Monitor           850000
18   Laptop          2500000
19    Mouse            85000
20  Teclado           120000
21  Monitor           850000
22   Laptop          2500000
23    Mouse            85000
24  Monitor           850000
25   Laptop          2500000
26  Teclado           120000
27    Mouse            85000
28  Monitor           850000
29   Laptop          2500000
30    Mouse            85000
31  Teclado           120000
32   Laptop          2500000
33  Monitor           850000
34    Mouse            85000
35   Laptop          2500000
36  Teclado           120000
37  Monitor           850000
38   Laptop          2500000
39    Mouse            85000
40  Teclado           120000
41  Monitor           850000
42   Laptop          2500000
43    Mouse            85000
44  Teclado           120000
45  Monitor           850000
46   Laptop          2500000
47    Mouse            85000
48  Teclado           120000
49  Monitor           850000
50   Laptop          2500000

In [65]:
#Mostrar únicamente productos mayores a $100.000.
ventas[ventas["Precio_Unitario"] > 100000][["Producto","Precio_Unitario"]]

   Producto  Precio_Unitario
0    Laptop          2500000
2   Teclado           120000
3   Monitor           850000
4    Laptop          2500000
6    Laptop          2500000
7    Laptop          2500000
8   Teclado           120000
9   Monitor           850000
10   Laptop          2500000
12  Teclado           120000
13  Monitor           850000
14   Laptop          2500000
16  Teclado           120000
17  Monitor           850000
18   Laptop          2500000
20  Teclado           120000
21  Monitor           850000
22   Laptop          2500000
24  Monitor           850000
25   Laptop          2500000
26  Teclado           120000
28  Monitor           850000
29   Laptop          2500000
31  Teclado           120000
32   Laptop          2500000
33  Monitor           850000
35   Laptop          2500000
36  Teclado           120000
37  Monitor           850000
38   Laptop          2500000
40  Teclado           120000
41  Monitor           850000
42   Laptop          2500000
44  Teclado           120000
45  Monitor           850000
46   Laptop          2500000
48  Teclado           120000
49  Monitor           850000
50   Laptop          2500000

In [74]:
# Crear una columna Precio Final.
ventas["Precio_final"] = (ventas["Precio_Unitario"]+ventas["IVA"])*ventas["Cantidad"]

ventas.head()

,ID_Venta,Fecha,Cliente,Ciudad,Producto,Categoría,Cantidad,Precio_Unitario,Estado,IVA,Precio_final
0,V001,2026-01-01,Ana Pérez,Pereira,Laptop,Tecnología,2.0,2500000,Completado,475000.0,5950000.0
1,V002,2026-01-02,Carlos Gómez,pereira,Mouse,tecnologia,5.0,85000,completado,16150.0,505750.0
2,V003,2026-01-03,María Díaz,PEREIRA,Teclado,Tecnología,3.0,120000,COMPLETADO,22800.0,428400.0
3,V004,2026-01-04,Juan López,Bogotá,Monitor,tecnologia,1.0,850000,Pendiente,161500.0,1011500.0
4,V005,2026-01-05,Laura Torres,bogota,Laptop,Tecnología,1.0,2500000,Completado,475000.0,2975000.0

In [75]:
#Mostrar únicamente productos de laptop.

ventas[ventas["Producto"] == "Laptop"]

,ID_Venta,Fecha,Cliente,Ciudad,Producto,Categoría,Cantidad,Precio_Unitario,Estado,IVA,Precio_final
0,V001,2026-01-01,Ana Pérez,Pereira,Laptop,Tecnología,2.0,2500000,Completado,475000.0,5950000.0
4,V005,2026-01-05,Laura Torres,bogota,Laptop,Tecnología,1.0,2500000,Completado,475000.0,2975000.0
6,V007,2026-01-07,Ana Pérez,Pereira,Laptop,Tecnología,2.0,2500000,Completado,475000.0,5950000.0
7,V007,2026-01-07,Ana Pérez,Pereira,Laptop,Tecnología,2.0,2500000,Completado,475000.0,5950000.0
10,V010,2026-01-10,Natalia Díaz,Bogotá,Laptop,Tecnología,1.0,2500000,Completado,475000.0,2975000.0
14,V014,2026-01-14,Valentina Cruz,PEREIRA,Laptop,Tecnología,1.0,2500000,Pendiente,475000.0,2975000.0
18,V018,2026-01-18,Sofía Castro,Cali,Laptop,Tecnología,2.0,2500000,Completado,475000.0,5950000.0
22,V022,2026-01-22,María Díaz,PEREIRA,Laptop,Tecnología,1.0,2500000,COMPLETADO,475000.0,2975000.0
25,V025,2026-01-25,Pedro Ruiz,Medellín,Laptop,Tecnología,2.0,2500000,Completado,475000.0,5950000.0
29,V029,2026-01-29,Camila Soto,Pereira,Laptop,tecnologia,1.0,2500000,Completado,475000.0,2975000.0
32,V032,2026-02-01,Andrés Rojas,Cali,Laptop,Tecnología,1.0,2500000,Pendiente,475000.0,2975000.0
35,V035,2026-02-04,María Díaz,PEREIRA,Laptop,Tecnología,1.0,2500000,COMPLETADO,475000.0,2975000.0
38,V038,2026-02-07,Pedro Ruiz,Medellín,Laptop,Tecnología,2.0,2500000,Completado,475000.0,5950000.0
42,V042,2026-02-11,Camila Soto,Pereira,Laptop,tecnologia,1.0,2500000,Completado,475000.0,2975000.0
46,V046,2026-02-15,Ana Pérez,Pereira,Laptop,Tecnología,1.0,2500000,Completado,475000.0,2975000.0
50,V050,2026-02-19,Laura Torres,bogota,Laptop,Tecnología,1.0,2500000,Completado,475000.0,2975000.0

In [ ]:
ventas.groupby("Ciudad")["Cantidad"].sum() #Esto sirve para agrupar datos pero se debe limpiar la base de datos

Ciudad
 Medellín      1.0
 Medellín      2.0
 Pereira       3.0
Bogotá        25.0
Cali          30.0
Medellín      15.0
PEREIRA       13.0
Pereira       31.0
bogota         7.0
pereira       18.0
Name: Cantidad, dtype: float64