Limpieza de datos
Valores duplicados
textos incompletos

In [1]:
import pandas as pd #siempre importarlo
import openpyxl #para usar excel
import csv #para usar archivos tipo .csv
pd.reset_option('display.max_rows')

In [2]:
df = pd.read_csv("df_ventas.csv")
df.head() #mostrar los primero siempre

,id_venta,fecha,cliente,ciudad,producto,categoria,cantidad,precio_unitario,descuento,metodo_pago,edad_cliente,vendedor
0,V1180,18/05/2026,Natalia Jiménez,MEDELLÍN,Laptop,TECNOLOGÍA,6,2500000,0,Daviplata,37.0,Luisa
1,V0343,2026/02/08,Gabriela Muñoz,ARMENIA,Mouse,Tecnología,3,45000,0%,Transferencia,56.0,Luisa
2,V0650,27/02/2026,Carlos Vargas,MANIZALES,Audífonos,Tecnología,5,180000,0.15,Transferencia,35.0,Diana
3,V0773,26/03/26,Luisa Fernández,cali,Mouse,TECNOLOGÍA,5,45000,0%,Efectivo,23.0,Diana
4,V0804,21/05/26,Camila Torres,bogotá,Bolígrafo,Papelería,4,3500,0%,Tarjeta,41.0,Carlos

In [3]:
df.shape

(1275, 12)

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1275 entries, 0 to 1274
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id_venta         1275 non-null   str
 1   fecha            1267 non-null   str
 2   cliente          1240 non-null   str
 3   ciudad           1249 non-null   str
 4   producto         1275 non-null   str
 5   categoria        1257 non-null   str
 6   cantidad         1275 non-null   int64
 7   precio_unitario  1263 non-null   str
 8   descuento        1255 non-null   str
 9   metodo_pago      1259 non-null   str
 10  edad_cliente     1247 non-null   float64
 11  vendedor         1265 non-null   str
dtypes: float64(1), int64(1), str(10)
memory usage: 119.7 KB

In [5]:
df.describe() #da informacion de las estadisticas que toma como numeros

          cantidad  edad_cliente
count  1275.000000   1247.000000
mean      3.385882     45.207698
std       1.804004     20.881328
min      -3.000000     -5.000000
25%       2.000000     30.000000
50%       3.000000     44.000000
75%       5.000000     59.000000
max       6.000000    200.000000

In [6]:
df.describe(include="all")

,id_venta,fecha,cliente,ciudad,producto,categoria,cantidad,precio_unitario,descuento,metodo_pago,edad_cliente,vendedor
count,1275,1267,1240,1249,1275,1257,1275.000000,1263,1255,1259,1247.000000,1265
unique,1250,726,34,30,15,17,NaN,33,10,8,NaN,6
top,V0044,10/07/26,Valentina Rodríguez,MANIZALES,Cuaderno,Tecnología,NaN,12000,15%,Nequi,NaN,Carlos
freq,2,6,65,70,100,144,NaN,92,207,264,NaN,229
mean,NaN,NaN,NaN,NaN,NaN,NaN,3.385882,NaN,NaN,NaN,45.207698,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,1.804004,NaN,NaN,NaN,20.881328,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,-3.000000,NaN,NaN,NaN,-5.000000,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,2.000000,NaN,NaN,NaN,30.000000,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,3.000000,NaN,NaN,NaN,44.000000,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,59.000000,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,6.000000,NaN,NaN,NaN,200.000000,NaN

VALORES FALTANTES

In [7]:
df.isnull() #busca en cada posicion y dice si es verd que no hay o si es
# falso que si hay

,id_venta,fecha,cliente,ciudad,producto,categoria,cantidad,precio_unitario,descuento,metodo_pago,edad_cliente,vendedor
0,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
1270,False,False,False,False,False,False,False,False,False,False,False,False
1271,False,False,False,False,False,False,False,False,False,False,False,False
1272,False,False,False,False,False,False,False,False,False,False,False,False
1273,False,False,False,False,False,False,False,False,False,False,False,False
1274,False,False,False,False,False,False,False,False,False,False,False,False

In [8]:
df.isnull().sum() #Tomca dada valor verdadero y los suma

id_venta            0
fecha               8
cliente            35
ciudad             26
producto            0
categoria          18
cantidad            0
precio_unitario    12
descuento          20
metodo_pago        16
edad_cliente       28
vendedor           10
dtype: int64

TRATAMIENTO DE VALORES NULOS

In [9]:
#OPCION A
#df.dropna() #Borra toda la fila donde aparezca un valor verdadero independi

In [10]:
#OPCION B
#df.dropna(subset=["ciudad"]) #Borra datos segun la columna especificada

In [11]:
#OPCION C
#df["ciudad"].fillna("Desconocida") #Llenar las celdas con un valor que doy

In [12]:
#OPCION D
#df["edad_cliente"].fillna(df["edad_cliente"].median()) #Se llena para variable numerica

In [13]:
df[df["ciudad"].isnull()].head(26) #para mostrar los valores nulos seg colum

,id_venta,fecha,cliente,ciudad,producto,categoria,cantidad,precio_unitario,descuento,metodo_pago,edad_cliente,vendedor
6,V0045,2026-05-01,Juliana Morales,NaN,Audífonos,tecnologia,4,180000,0.15,Daviplata,25.0,Andrés
40,V0129,11/07/26,Laura Gómez,NaN,Impresora,TECNOLOGÍA,5,650000,10%,Tarjeta,60.0,Felipe
47,V0583,13/03/2026,Sofía Ramírez,NaN,Impresora,TECNOLOGÍA,-3,650000,0%,Daviplata,25.0,Felipe
163,V1134,2026-01-31,Pedro Ruiz,NaN,Celular,Tecnología,4,1800000,15%,Daviplata,NaN,Diana
202,V1220,28-03-2026,Camila Torres,NaN,Bolígrafo,papeleria,6,3500,5%,Tarjeta,-5.0,María
210,V0523,27/06/2026,Sofía Ramírez,NaN,Cuaderno,Papelería,6,12000,15%,Tarjeta,18.0,Carlos
214,V1170,03/06/2026,Juliana Morales,NaN,Teclado,Tecnología,1,120000,15%,Transferencia,37.0,María
291,V1043,25-06-2026,Luisa Fernández,NaN,Bolígrafo,PAPELERÍA,3,3500,0%,Tarjeta,43.0,Felipe
318,V0629,17-07-2026,Manuela Cárdenas,NaN,Cuaderno,papeleria,5,12000,5%,Efectivo,42.0,Andrés
384,V1033,2026-06-18,Luisa Fernández,NaN,Cuaderno,papeleria,3,12000,0%,Transferencia,34.0,Felipe
448,V0129,11/07/26,Laura Gómez,NaN,Impresora,TECNOLOGÍA,5,650000,10%,Tarjeta,60.0,Felipe
488,V0937,2026-02-11,Nicolás Quintero,NaN,Mouse,Tecnología,1,45000,0.1,Transferencia,28.0,Luisa
497,V0812,20/06/26,Sofía Ramírez,NaN,Mochila,ACCESORIOS,4,140000,15%,Transferencia,64.0,Carlos
572,V0721,13/07/2026,Manuela Cárdenas,NaN,Teclado,Tecnología,1,120000,0.05,Nequi,25.0,Luisa
615,V0008,2026/04/22,Manuela Cárdenas,NaN,Audífonos,TECNOLOGÍA,2,0,15%,Efectivo,29.0,Felipe
794,V0397,06/04/2026,Gabriela Muñoz,NaN,Impresora,tecnologia,3,650000,0%,Tarjeta,28.0,Carlos
845,V1152,2026/05/29,Laura Gómez,NaN,Maletín,ACCESORIOS,1,190000,0%,Daviplata,20.0,Carlos
870,V1146,2026/04/04,Pedro Ruiz,NaN,Mouse,TECNOLOGÍA,4,45000,5%,Tarjeta,52.0,Diana
888,V0831,18/05/26,Camila Torres,NaN,Laptop,Tecnología,1,2500000,10%,Nequi,28.0,Luisa
971,V0155,25-05-2026,Daniel Moreno,NaN,Mouse,Tecnologia,2,45000,20%,Efectivo,64.0,Diana
998,V0993,01/02/2026,Juliana Morales,NaN,Escritorio,Oficina,2,580000,15%,Daviplata,60.0,Diana
999,V1246,11/07/2026,Natalia Jiménez,NaN,Tablet,tecnologia,1,1100000,20%,Nequi,69.0,Felipe
1026,V1020,2026-02-19,Andrés Martínez,NaN,Mochila,Accesorios,3,140000,15%,Tarjeta,50.0,Diana
1071,V0897,2026/01/18,Valentina Rodríguez,NaN,Mouse,Tecnología,3,45000,15%,Daviplata,62.0,Luisa
1131,V1176,05/07/2026,Alejandro Ortiz,NaN,Monitor,tecnologia,3,850000,0%,Transferencia,53.0,Diana
1226,V0565,18/05/26,Felipe Arias,NaN,Teclado,tecnologia,2,120000,0%,Transferencia,63.0,Luisa

In [14]:
#Tambien puedo usar una funcion condicional para unir la columna del vended
#junto con la ciudad y así se puede salvar info
df["ciudad"] = df["ciudad"].fillna("Desconocida")

In [15]:
#Para la edad del ciente se usa la mediana y no la media? 
#Porque con la mediana se llena max y min de edad y coge uno en medio

mediana_edad = df["edad_cliente"].median()

df["edad_cliente"] = df["edad_cliente"].fillna(mediana_edad)

mediana_edad

np.float64(44.0)

In [16]:
df.isnull().sum()

id_venta            0
fecha               8
cliente            35
ciudad              0
producto            0
categoria          18
cantidad            0
precio_unitario    12
descuento          20
metodo_pago        16
edad_cliente        0
vendedor           10
dtype: int64

DUPLICADOS

In [17]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
1270    False
1271    False
1272    False
1273    False
1274    False
Length: 1275, dtype: bool

In [18]:
df.duplicated().sum()

np.int64(24)

In [19]:
df[df.duplicated()].head(24) #Toda esta info esta duplicada

,id_venta,fecha,cliente,ciudad,producto,categoria,cantidad,precio_unitario,descuento,metodo_pago,edad_cliente,vendedor
53,V1044,13/07/26,Laura Gómez,Bogotá,Celular,Tecnología,4,1800000,10%,Nequi,25.0,María
106,V0514,22/05/26,Ana Pérez,Armenia,Bolígrafo,papeleria,4,3500,15%,Transferencia,62.0,Diana
348,V0681,07/06/26,Juliana Morales,Pereira,Mouse,tecnologia,3,45000,10%,Tarjeta,200.0,Carlos
371,V1051,2026-03-20,Sofía Ramírez,Armenia,Bolígrafo,papeleria,3,3500,5%,Tarjeta,59.0,Andrés
396,V0498,25-07-2026,Pedro Ruiz,Dosquebradas,Maletín,Accesorios,4,190000,0%,Nequi,53.0,Luisa
397,V1171,09-07-2026,Mateo Díaz,Pereira,Mochila,Accesorios,5,140000,10%,Transferencia,69.0,Luisa
448,V0129,11/07/26,Laura Gómez,Desconocida,Impresora,TECNOLOGÍA,5,650000,10%,Tarjeta,60.0,Felipe
458,V1168,08/02/2026,Juan López,Medellín,Agenda,Papelería,2,25000,0.05,Transferencia,62.0,Carlos
485,V0395,2026-02-22,Daniel Moreno,Cali,Mochila,Accesorios,5,140000,0%,Efectivo,40.0,Felipe
491,V0744,18-07-2026,Paula Sánchez,Cali,Silla ergonómica,Oficina,3,720000,0%,Efectivo,62.0,Andrés
534,V0779,09/05/2026,Valentina Rodríguez,Dosquebradas,Audífonos,tecnologia,3,180000,0.1,Daviplata,31.0,Diana
546,V0210,22/04/26,Sofía Ramírez,MANIZALES,Cuaderno,Papelería,2,12000,0.05,Tarjeta,22.0,Diana
691,V0271,01-01-2026,Carlos Vargas,Bogotá,Mochila,accesorios,6,140000,15%,Transferencia,32.0,Luisa
769,V0463,08/07/2026,Valentina Rodríguez,Medellín,Cuaderno,Papelería,3,12000,15%,Nequi,65.0,Luisa
824,V0946,17/03/2026,Gabriela Muñoz,Medellín,Audífonos,Tecnología,6,180000,0.15,Tarjeta,60.0,Felipe
952,V1140,2026-02-28,Ana Pérez,cartago,Celular,Tecnología,4,1800000,0%,NaN,69.0,Felipe
969,V0044,14/03/26,Daniel Moreno,Medellín,Escritorio,Oficina,1,580000,5%,Tarjeta,26.0,Felipe
976,V0943,2026-05-01,Juan López,MEDELLÍN,Laptop,TECNOLOGÍA,2,2500000,0%,Tarjeta,70.0,Carlos
984,V0082,2026-01-28,Luisa Fernández,Bogota,Mochila,accesorios,2,140000,15%,Transferencia,39.0,Andrés
995,V1103,04-02-2026,Gabriela Muñoz,PEREIRA,Escritorio,Oficina,6,$580.000,20%,Tarjeta,48.0,Luisa
1035,V1240,21-03-2026,Camila Torres,Medellín,Agenda,papeleria,6,25000,0%,Efectivo,25.0,Carlos
1041,V0931,2026-04-22,Santiago Hernández,cartago,Monitor,Tecnologia,6,850000,5%,Nequi,68.0,Luisa
1044,V1119,12/05/26,Valentina Rodríguez,ARMENIA,Audífonos,Tecnología,1,180000,0.15,Nequi,41.0,Felipe
1223,V0951,24/02/26,Felipe Arias,Cali,Monitor,Tecnología,2,850000,10%,Nequi,43.0,Diana

ELIMINAR DUPLICADOS EXACTOS

In [20]:
df = df.drop_duplicates()

df.shape

# .drop() - Elimina algo

(1251, 12)

LIMPIEZA DE TEXTOS

Los más importantes:

.str.strip() → elimina espacios al inicio y final

.str.lower() → minúsculas

.str.upper() → mayúsculas

.str.title() → Iniciales en mayúscula

.str.replace() → reemplazar texto

In [21]:
df["ciudad"].value_counts() #contar las celdas iguales

ciudad
MANIZALES       69
armenia         69
CARTAGO         65
dosquebradas    62
Dosquebradas    58
Manizales       51
Armenia         50
 Medellín       47
cali            46
cartago         45
medellin        41
manizales       41
 Bogotá         40
 Cali           39
MEDELLÍN        37
Cartago         37
Medellín        37
BOGOTA          36
CALI            35
ARMENIA         34
pereira         34
DOSQUEBRADAS    32
PEREIRA         31
Bogotá          30
Bogota          28
Cali            28
bogotá          27
 Pereira        26
Pereira         26
Desconocida     25
Pereira         25
Name: count, dtype: int64

In [22]:
df["ciudad"] = (
    df["ciudad"]
    .str.strip()
    .str.lower()
    .str.title()
)

df["ciudad"].value_counts()

ciudad
Manizales       161
Armenia         153
Dosquebradas    152
Cali            148
Cartago         147
Pereira         142
Medellín        121
Bogotá           97
Bogota           64
Medellin         41
Desconocida      25
Name: count, dtype: int64

In [23]:
df["ciudad"] = (
    df["ciudad"]
    .str.replace("Medellin", "Medellín", regex=False)
    .str.replace("Bogota", "Bogotá", regex=False)
)
#La funcion sirve para reemplazar medellin a como Medellín

df["ciudad"].value_counts()

ciudad
Medellín        162
Manizales       161
Bogotá          161
Armenia         153
Dosquebradas    152
Cali            148
Cartago         147
Pereira         142
Desconocida      25
Name: count, dtype: int64

In [24]:
df["categoria"].value_counts()

categoria
Tecnología      140
tecnologia      139
 Tecnologia     133
Tecnología      127
TECNOLOGÍA      122
Papelería        63
papeleria        62
 Papelería       61
PAPELERÍA        58
Oficina          51
accesorios       45
Accesorios       45
ACCESORIOS       42
oficina          42
 Oficina         41
OFICINA          38
 Accesorios      24
Name: count, dtype: int64

In [25]:
df["categoria"] = (
    df["categoria"]
    .str.strip()
    .str.lower()
    .str.title()
)

df["categoria"].value_counts()

categoria
Tecnología    389
Tecnologia    272
Papelería     182
Oficina       172
Accesorios    156
Papeleria      62
Name: count, dtype: int64

In [26]:
df["categoria"] = (
    df["categoria"]
    .str.replace("Tecnología", "Tecnologia", regex=False)
    .str.replace("Papelería", "Papeleria", regex=False)
)

df["categoria"].value_counts()

categoria
Tecnologia    661
Papeleria     244
Oficina       172
Accesorios    156
Name: count, dtype: int64

LIMPIAR NOMBRES CLIENTES

In [27]:
df["cliente"] = df["cliente"].str.strip()

TIPO DE DATOS

In [28]:
df.info()

<class 'pandas.DataFrame'>
Index: 1251 entries, 0 to 1274
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id_venta         1251 non-null   str
 1   fecha            1243 non-null   str
 2   cliente          1216 non-null   str
 3   ciudad           1251 non-null   str
 4   producto         1251 non-null   str
 5   categoria        1233 non-null   str
 6   cantidad         1251 non-null   int64
 7   precio_unitario  1239 non-null   str
 8   descuento        1231 non-null   str
 9   metodo_pago      1236 non-null   str
 10  edad_cliente     1251 non-null   float64
 11  vendedor         1241 non-null   str
dtypes: float64(1), int64(1), str(10)
memory usage: 127.1 KB

PRECIO UNITARIO

In [29]:
df["precio_unitario"].head(10)

0       2500000
1         45000
2        180000
3         45000
4          3500
5    $1.100.000
6        180000
7        140000
8         25000
9        580000
Name: precio_unitario, dtype: str

In [30]:
df["precio_unitario"] = (
    df["precio_unitario"]
    .astype("string") # .astype () - convierte columna a texto
    .str.replace("$", "", regex=False)
    .str.replace(".", "", regex=False) # regex=False = busca exactamente ese texto, sin interpretarlo como una expresión regular
)

df["precio_unitario"].head(10)

0    2500000
1      45000
2     180000
3      45000
4       3500
5    1100000
6     180000
7     140000
8      25000
9     580000
Name: precio_unitario, dtype: string

Convertir a número

pd.to_numeric() intenta convertir los valores a un tipo numérico.

Con errors="coerce" los valores que no puedan convertirse pasan a ser NaN

In [31]:
df["precio_unitario"] = pd.to_numeric(
    df["precio_unitario"],
    errors="coerce"
)

df["precio_unitario"].dtype

Int64Dtype()

In [32]:
df.info()

<class 'pandas.DataFrame'>
Index: 1251 entries, 0 to 1274
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id_venta         1251 non-null   str
 1   fecha            1243 non-null   str
 2   cliente          1216 non-null   str
 3   ciudad           1251 non-null   str
 4   producto         1251 non-null   str
 5   categoria        1233 non-null   str
 6   cantidad         1251 non-null   int64
 7   precio_unitario  1239 non-null   Int64
 8   descuento        1231 non-null   str
 9   metodo_pago      1236 non-null   str
 10  edad_cliente     1251 non-null   float64
 11  vendedor         1241 non-null   str
dtypes: Int64(1), float64(1), int64(1), str(9)
memory usage: 128.3 KB

In [33]:
df["descuento"].head(10)

0       0
1      0%
2    0.15
3      0%
4      0%
5      5%
6    0.15
7     10%
8     15%
9      5%
Name: descuento, dtype: str

In [ ]:
df["descuento"] = (
    df["descuento"]
    .astype("string") #se convierte la columna a texto
    .str.replace("%", "", regex=False)
)

df["descuento"] = pd.to_numeric( #se pasa a valor numerico
    df["descuento"],
    errors="coerce"
)

Ahora tenemos los porcentajes como números.

Para trabajar con el descuento en cálculos, se puede convertir a proporción:

10 → 0.10

5 → 0.05

In [38]:
df["descuento"] = df["descuento"] / 100

df["descuento"].head(10)

0         0.0
1         0.0
2    0.000015
3         0.0
4         0.0
5      0.0005
6    0.000015
7       0.001
8      0.0015
9      0.0005
Name: descuento, dtype: Float64

In [37]:
df["fecha"].head(10)

0    18/05/2026
1    2026/02/08
2    27/02/2026
3      26/03/26
4      21/05/26
5    01-04-2026
6    2026-05-01
7    45/05/2026
8      20/07/26
9      14/03/26
Name: fecha, dtype: str

Se encuentran formatos diferentes:

2026-01-05

05/01/2026

2026/01/07

08-01-2026

In [39]:
df["fecha"] = pd.to_datetime( #lo convierte a formato de fecha
    df["fecha"],
    errors="coerce",
    format="mixed",
    dayfirst=True #si empieza por el dia la fecha 13-10-2026
)

¿Qué significa NaT?

NaT significa Not a Time.

Es el equivalente a un valor faltante para fechas y tiempos.

In [40]:
df[df["fecha"].isnull()]

,id_venta,fecha,cliente,ciudad,producto,categoria,cantidad,precio_unitario,descuento,metodo_pago,edad_cliente,vendedor
7,V0232,NaT,Sofía Ramírez,Armenia,Mochila,Accesorios,0,140000,0.001,Tarjeta,66.0,Andrés
11,V0064,NaT,Luisa Fernández,Manizales,Escritorio,Oficina,6,580000,0.0005,Nequi,26.0,Andrés
216,V1088,NaT,Laura Gómez,Cartago,Bolígrafo,Papeleria,2,3500,0.001,Daviplata,67.0,Carlos
241,V0920,NaT,Natalia Jiménez,Pereira,Mochila,Accesorios,4,140000,0.0015,Efectivo,46.0,Diana
244,V0332,NaT,Gabriela Muñoz,Bogotá,Laptop,Tecnologia,4,2500000,0.002,Nequi,38.0,Diana
347,V1167,NaT,Camila Torres,Pereira,Mochila,Accesorios,0,140000,0.0,Transferencia,63.0,Diana
361,V0040,NaT,Nicolás Quintero,Dosquebradas,Mochila,Accesorios,5,140000,0.001,Nequi,46.0,Andrés
363,V0243,NaT,Daniel Moreno,Armenia,Maletín,Accesorios,2,190000,<NA>,Efectivo,26.0,María
387,V0967,NaT,Mateo Díaz,Cali,Agenda,Papeleria,6,25000,0.00002,Efectivo,54.0,Felipe
446,V1030,NaT,Diego Restrepo,Armenia,Cuaderno,Papeleria,4,12000,0.000005,Transferencia,33.0,María
461,V0107,NaT,Sebastián Rojas,Pereira,Mouse,Tecnologia,3,45000,0.0,Efectivo,67.0,Andrés
478,V0885,NaT,Mateo Díaz,Manizales,Monitor,Tecnologia,3,850000,0.0005,Tarjeta,43.0,Felipe
557,V0072,NaT,Manuela Cárdenas,Armenia,Mochila,Accesorios,4,140000,0.0,Nequi,56.0,Felipe
726,V0849,NaT,Sebastián Rojas,Pereira,Silla ergonómica,Oficina,4,720000,0.001,Transferencia,59.0,Felipe
781,V0418,NaT,Luisa Fernández,Manizales,Bolígrafo,Papeleria,5,3500,0.002,Tarjeta,48.0,Carlos
992,V0983,NaT,Laura Gómez,Medellín,Agenda,Papeleria,2,25000,0.0015,Nequi,44.0,María

In [42]:
df["fecha"].head(10)

0   2026-05-18
1   2026-08-02
2   2026-02-27
3   2026-03-26
4   2026-05-21
5   2026-04-01
6   2026-01-05
7          NaT
8   2026-07-20
9   2026-03-14
Name: fecha, dtype: datetime64[us]

In [41]:
df.shape

(1251, 12)

Valores inválidos

Un dato puede tener el tipo correcto y aun así estar mal.

Ejemplo:

edad_cliente = 150
cantidad = -3

In [43]:
df[df["edad_cliente"] < 18][["id_venta", "cliente", "edad_cliente"]].head(20)

     id_venta              cliente  edad_cliente
87      V1136           Mateo Díaz           0.0
202     V1220        Camila Torres          -5.0
337     V0275         Felipe Arias          -5.0
482     V1076      Luisa Fernández          -5.0
628     V0526  Valentina Rodríguez          -5.0
673     V0070      Andrés Martínez           0.0
725     V0949          Laura Gómez           0.0
935     V0354       Diego Restrepo           0.0
1057    V1071         Felipe Arias           0.0
1088    V0147          Laura Gómez           0.0
1264    V1124            Ana Pérez           0.0
1273    V0861      Natalia Jiménez           0.0

In [44]:
df[
    (df["edad_cliente"] < 18) |
    (df["edad_cliente"] > 100)
][["id_venta", "cliente", "edad_cliente"]].head(20)

     id_venta              cliente  edad_cliente
79      V0860          Laura Gómez         150.0
87      V1136           Mateo Díaz           0.0
202     V1220        Camila Torres          -5.0
228     V0681      Juliana Morales         200.0
249     V0995       Diego Restrepo         150.0
260     V1079      Luisa Fernández         200.0
337     V0275         Felipe Arias          -5.0
462     V0950        Carlos Vargas         150.0
482     V1076      Luisa Fernández          -5.0
536     V0335  Valentina Rodríguez         150.0
617     V0954           Mateo Díaz         150.0
628     V0526  Valentina Rodríguez          -5.0
673     V0070      Andrés Martínez           0.0
694     V0799        Camila Torres         200.0
725     V0949          Laura Gómez           0.0
935     V0354       Diego Restrepo           0.0
1057    V1071         Felipe Arias           0.0
1060    V1129      Natalia Jiménez         200.0
1088    V0147          Laura Gómez           0.0
1103    V1158            Ana Pérez         200.0

In [45]:
condicion_edad = (
    (df["edad_cliente"] < 18) |
    (df["edad_cliente"] > 100)
)

df.loc[condicion_edad, "edad_cliente"] = pd.NA

In [46]:
df[df["edad_cliente"].isnull()]

,id_venta,fecha,cliente,ciudad,producto,categoria,cantidad,precio_unitario,descuento,metodo_pago,edad_cliente,vendedor
79,V0860,2026-04-06,Laura Gómez,Medellín,Teclado,Tecnologia,1,120000,0.0005,Tarjeta,NaN,Felipe
87,V1136,2026-06-24,Mateo Díaz,Pereira,Celular,Tecnologia,3,1800000,0.00001,Tarjeta,NaN,Carlos
202,V1220,2026-03-28,Camila Torres,Desconocida,Bolígrafo,Papeleria,6,3500,0.0005,Tarjeta,NaN,María
228,V0681,2026-06-07,Juliana Morales,Pereira,Mouse,Tecnologia,3,45000,0.001,Tarjeta,NaN,Carlos
249,V0995,2026-01-13,Diego Restrepo,Cartago,Bolígrafo,Papeleria,1,3500,0.000015,Daviplata,NaN,María
260,V1079,2026-05-16,Luisa Fernández,Armenia,Celular,Tecnologia,3,1800000,0.0015,Nequi,NaN,Felipe
337,V0275,2026-04-13,Felipe Arias,Dosquebradas,Silla ergonómica,Oficina,3,720000,0.002,Transferencia,NaN,María
462,V0950,2026-05-12,Carlos Vargas,Armenia,Monitor,Tecnologia,5,850000,0.0015,Nequi,NaN,Felipe
482,V1076,2026-02-14,Luisa Fernández,Bogotá,Tablet,Tecnologia,2,1100000,0.001,Tarjeta,NaN,Diana
536,V0335,2026-05-07,Valentina Rodríguez,Pereira,Maletín,Accesorios,2,190000,0.0005,Tarjeta,NaN,Diana
617,V0954,2026-04-21,Mateo Díaz,Cali,Laptop,Tecnologia,1,2500000,0.0,Efectivo,NaN,Luisa
628,V0526,2026-02-01,Valentina Rodríguez,Bogotá,Escritorio,Oficina,1,580000,0.0015,Efectivo,NaN,Diana
673,V0070,2026-12-03,Andrés Martínez,Manizales,Laptop,Tecnologia,2,2500000,0.000005,Nequi,NaN,Felipe
694,V0799,2026-02-05,Camila Torres,Armenia,Mouse,Tecnologia,4,45000,0.0015,Transferencia,NaN,Felipe
725,V0949,2026-03-25,Laura Gómez,Cartago,Mochila,Accesorios,6,140000,0.000015,Tarjeta,NaN,María
935,V0354,2026-06-19,Diego Restrepo,Manizales,Cuaderno,Papeleria,1,12000,0.0,Efectivo,NaN,María
1057,V1071,2026-04-04,Felipe Arias,Armenia,Agenda,Papeleria,3,25000,0.0015,Tarjeta,NaN,Carlos
1060,V1129,2026-05-04,Natalia Jiménez,Manizales,Tablet,Tecnologia,3,1100000,0.0,NaN,NaN,Felipe
1088,V0147,2026-01-12,Laura Gómez,Manizales,Audífonos,Tecnologia,1,180000,0.00001,Efectivo,NaN,Felipe
1103,V1158,2026-01-09,Ana Pérez,Medellín,Bolígrafo,Papeleria,5,3500,0.0,Nequi,NaN,NaN
1154,V0795,2026-06-16,Juan López,Medellín,Tablet,Tecnologia,3,1100000,0.0005,Daviplata,NaN,Carlos
1264,V1124,2026-12-05,Ana Pérez,Bogotá,Silla ergonómica,Oficina,1,720000,0.002,Nequi,NaN,Luisa
1273,V0861,2026-01-15,Natalia Jiménez,Armenia,Mouse,Tecnologia,6,45000,0.0005,Efectivo,NaN,Luisa

In [47]:
df[df["cantidad"] <= 0][
    ["id_venta", "producto", "cantidad"]
]

     id_venta    producto  cantidad
7       V0232     Mochila         0
47      V0583   Impresora        -3
52      V0307  Escritorio         0
115     V0334      Laptop        -1
136     V1132      Tablet         0
209     V0478     Teclado        -3
251     V1106      Tablet        -1
347     V1167     Mochila         0
354     V0543   Audífonos        -1
366     V0311  Escritorio         0
395     V0712  Escritorio        -3
476     V0561      Agenda        -1
480     V0631   Audífonos         0
558     V0095       Mouse        -3
612     V0786     Celular         0
620     V0794     Celular        -1
650     V0505     Monitor        -3
690     V0194   Audífonos        -1
693     V0170       Mouse        -3
735     V1250  Escritorio        -3
762     V0689    Cuaderno         0
901     V0047  Escritorio        -1
928     V0698       Mouse         0
1086    V0489     Monitor        -1
1183    V0593     Maletín         0
1217    V1026     Maletín         0
1268    V0467      Agenda        -1
1274    V1127    Cuaderno        -3

In [48]:
df = df[df["cantidad"] > 0].copy()

REVISION DE PRECIOS